#!/bin/bash

# Append 4 numbers with first uppercase

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function entry {
   local name=$1

   source $DIR/2num-suffix
   entry "$(tr '[:lower:]' '[:upper:]' <<< ${name:0:1})${name:1}"
}
