#!/bin/bash

# Append 4 numbers

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/common.sh

function entry {
   local name=$1

   name_size=$(getStringSize $name)

   total_length=$(($name_size + 4))

   if [[ $total_length -lt 8 ]]; then
      >&2 echo "`basename ${BASH_SOURCE[0]}`: '$name' too short"
      return
   fi

   crunch $total_length $total_length $(tr '[:lower:]' '[:upper:]' <<< ${name:0:1})$(tr '[:upper:]' '[:lower:]' <<< ${name:0:1}) 0123456789 -t @${name:1}%%%% 2>/dev/null
}
