#!/bin/bash


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/common.sh

function entry {
   local name=$1

   name_size=$(getStringSize $name)

   if [[ $name_size -lt 8 ]]; then
      >&2 echo "'$name' too short"
      return
   fi

   echo "$name"
}
